export const initialJobs = [
  {
    title: 'Frontend Developer Intern',
    company: 'TechCorp Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=100&auto=format&fit=crop&q=80',
    description: 'We are seeking an enthusiastic Frontend Developer Intern to join our modern web development team. You will collaborate with designers and senior engineers to build responsive, accessible, and fast web interfaces using modern React and Tailwind CSS.',
    responsibilities: [
      'Build responsive UI components using React and Tailwind CSS',
      'Collaborate with UX designers to translate Figma mockups into pixel-perfect code',
      'Integrate REST APIs and optimize client-side performance',
      'Participate in daily standups and code reviews with senior mentors',
    ],
    requirements: [
      'Basic knowledge of HTML5, CSS3, JavaScript (ES6+), and React.js',
      'Familiarity with Git and GitHub version control',
      'Strong problem-solving mindset and eagerness to learn',
      'College student in penultimate/final year or recent graduate',
    ],
    qualifications: [
      'Pursuing or completed B.Tech / B.E. / BCA / MCA / B.Sc in Computer Science or related branch',
      'Good academic record (6.5+ CGPA preferred)',
    ],
    skills: ['React', 'JavaScript', 'HTML5', 'CSS3', 'Tailwind CSS', 'Git'],
    location: 'Remote',
    workMode: 'Remote',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹25,000 / month',
    benefits: ['Certificate of Internship', 'Letter of Recommendation', 'Flexible Hours', 'Mentorship Program', 'Pre-Placement Offer (PPO) potential'],
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'React Developer Intern',
    company: 'InnoWave Labs',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    description: 'Join InnoWave Labs as a React Developer Intern! You will work on cutting-edge SaaS dashboards, real-time data visualisations, and customer-facing web applications alongside experienced full-stack mentors.',
    responsibilities: [
      'Develop modern reusable React components with TypeScript',
      'State management using Redux Toolkit / Zustand',
      'Assist with unit and component testing',
      'Fix UI bugs and improve cross-browser compatibility',
    ],
    requirements: [
      'Hands-on experience with React projects (academic or personal projects)',
      'Familiarity with TypeScript and modern CSS frameworks',
      'Understanding of asynchronous programming and fetch/Axios',
    ],
    qualifications: [
      'Enrolled in or graduated from an accredited Computer Science or Information Technology program',
      'Portfolio or GitHub repositories demonstrating frontend projects',
    ],
    skills: ['React', 'TypeScript', 'Redux', 'REST APIs', 'CSS3'],
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹30,000 / month',
    benefits: ['Hybrid Work Allowance', 'Free Lunches & Snacks', 'Access to Learning Subscriptions', 'PPO on good performance'],
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Python Developer Intern',
    company: 'PySphere AI',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80',
    description: 'PySphere AI is hiring a motivated Python Developer Intern to contribute to backend service microservices, automated data scrapers, and data pipelines. Great opportunity to learn production backend architecture.',
    responsibilities: [
      'Write clean, modular, and well-documented Python scripts',
      'Assist in developing RESTful endpoints with FastAPI/Django',
      'Write unit tests and perform database migrations with PostgreSQL',
      'Investigate API errors and optimize server performance',
    ],
    requirements: [
      'Solid command of Python 3 syntax and data structures',
      'Basic understanding of relational databases (SQL, PostgreSQL)',
      'Basic knowledge of HTTP protocols and web APIs',
    ],
    qualifications: [
      'B.Tech / B.E. / BCA / MCA in CS, IT, or Electronics',
      'Passion for backend systems and backend engineering',
    ],
    skills: ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Git', 'REST API'],
    location: 'Remote',
    workMode: 'Remote',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹28,000 / month',
    benefits: ['Remote Work Stipend', 'Mentorship from Senior Architects', 'Certificate of Completion'],
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Machine Learning Intern',
    company: 'CogniData Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    description: 'Explore the real-world application of AI/ML algorithms in computer vision, tabular modeling, and NLP. Ideal for students with strong mathematical aptitude and Python programming capabilities.',
    responsibilities: [
      'Perform data preprocessing, exploratory data analysis, and feature engineering',
      'Train baseline machine learning models with Scikit-Learn and PyTorch',
      'Evaluate model metrics and present findings to data science leads',
      'Document experimentation methodologies and hyperparameter results',
    ],
    requirements: [
      'Proficiency in Python and libraries like NumPy, Pandas, Matplotlib, and Scikit-Learn',
      'Understanding of core ML algorithms (linear models, trees, neural nets)',
      'Strong foundation in probability, statistics, and linear algebra',
    ],
    qualifications: [
      '3rd or 4th year undergraduate student or Master’s in Data Science, CS, AI, or Math',
    ],
    skills: ['Python', 'Machine Learning', 'PyTorch', 'Pandas', 'NumPy', 'Scikit-Learn'],
    location: 'Hyderabad, Telangana',
    workMode: 'On-site',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹35,000 / month',
    benefits: ['High-performance GPU cluster access', 'Research paper publication support', 'Internship completion bonus'],
    postedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Data Analyst Intern',
    company: 'QuantMetrics Analytics',
    companyLogo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&auto=format&fit=crop&q=80',
    description: 'We are looking for an inquisitive Data Analyst Intern to turn raw business data into actionable visual insights, interactive KPI dashboards, and automated management reports.',
    responsibilities: [
      'Query relational databases using SQL to extract operational metrics',
      'Design interactive dashboards in Power BI and Google Data Studio',
      'Cleanse messy datasets using Excel and Python',
      'Present weekly performance trends to internal stakeholders',
    ],
    requirements: [
      'Working knowledge of SQL (SELECT, JOIN, GROUP BY, aggregations)',
      'Proficiency with MS Excel (VLOOKUP, Pivot Tables, Formulas)',
      'Basic familiarity with Power BI, Tableau, or Python data libraries',
    ],
    qualifications: [
      'B.Com, BBA, B.Sc, BCA, or B.Tech with an inclination for data analysis',
    ],
    skills: ['SQL', 'Excel', 'Power BI', 'Python', 'Data Analysis'],
    location: 'Pune, Maharashtra',
    workMode: 'Hybrid',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹22,000 / month',
    benefits: ['Hybrid flexibility (2 days in-office)', 'Certification vouchers', 'Mentorship'],
    postedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Full Stack Developer',
    company: 'CloudNexa Systems',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=100&auto=format&fit=crop&q=80',
    description: 'CloudNexa is hiring entry-level Full Stack Engineers to build cloud-native applications. You will work across both client-side React/Next.js interfaces and Node.js microservices backed by MongoDB.',
    responsibilities: [
      'Build end-to-end web features from database schema to responsive UI',
      'Create high-performance REST APIs and integrate third-party services',
      'Write comprehensive unit and integration tests',
      'Participate in architectural reviews and deployment automation',
    ],
    requirements: [
      'Solid understanding of JavaScript/TypeScript, React, Node.js, and MongoDB',
      'Familiarity with Git, REST principles, and asynchronous programming',
      'Good communication skills and eagerness to take ownership of features',
    ],
    qualifications: [
      'B.Tech / B.E. / MCA in Computer Science, IT, or related fields (2024 / 2025 / 2026 batches)',
    ],
    skills: ['Next.js', 'React', 'Node.js', 'MongoDB', 'TypeScript', 'REST API'],
    location: 'Remote',
    workMode: 'Remote',
    jobType: 'Full Time',
    experienceLevel: 'Entry Level',
    salary: '₹6.5 - 8.5 LPA',
    benefits: ['Health Insurance', 'Home Office Setup Allowance', 'Annual Learning Budget', 'Paid Time Off', 'Stock Options'],
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Software Engineer - Fresher',
    company: 'Apex Global Systems',
    companyLogo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&auto=format&fit=crop&q=80',
    description: 'Kickstart your engineering career with Apex Global Systems! We provide a comprehensive 3-month foundational training program followed by assignment to enterprise cloud transformation projects.',
    responsibilities: [
      'Write clean, maintainable, and efficient code in Java or C++',
      'Collaborate with agile sprint teams to deliver enterprise software modules',
      'Participate in automated testing, code reviews, and defect triage',
      'Learn cloud architectures, DevOps tooling, and distributed systems',
    ],
    requirements: [
      'Strong foundation in Data Structures, Algorithms, and Object-Oriented Design',
      'Proficiency in Java, C++, or Python',
      'Understanding of relational databases and SQL queries',
    ],
    qualifications: [
      'B.Tech / B.E. in CS / IT / ECE / EEE (60% or 6.5 CGPA throughout academics)',
      '2024, 2025, or 2026 graduating students eligible',
    ],
    skills: ['Java', 'Spring Boot', 'SQL', 'Data Structures', 'Algorithms', 'OOP'],
    location: 'Bengaluru, Karnataka',
    workMode: 'On-site',
    jobType: 'Full Time',
    experienceLevel: 'Fresher',
    salary: '₹5.5 - 7.0 LPA',
    benefits: ['Comprehensive Medical Coverage', 'Cab Facility / Transport Allowance', 'Subsidized Cafeteria', 'Higher Education Assistance'],
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'AI/ML Engineer - Fresher',
    company: 'NeuralPulse Tech',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    description: 'Exciting full-time opportunity for fresh graduates with deep passion for generative AI, large language models (LLMs), and retrieval-augmented generation (RAG) architectures.',
    responsibilities: [
      'Develop AI agents and prompt engineering pipelines for enterprise customers',
      'Integrate LLMs with vector databases like Pinecone/Chroma and LangChain/LlamaIndex',
      'Build backend microservices using FastAPI and Docker',
      'Continuously benchmark model latency, accuracy, and hallucination rates',
    ],
    requirements: [
      'Strong programming capability in Python 3',
      'Familiarity with LangChain, OpenAI APIs, or open-source Hugging Face models',
      'Basic knowledge of vector embeddings, fine-tuning, and prompt optimization',
    ],
    qualifications: [
      'B.Tech / M.Tech / MS in CS, AI, Data Science, or allied disciplines',
      'Hands-on projects or open source contributions in AI/ML domain',
    ],
    skills: ['Python', 'FastAPI', 'LLMs', 'NLP', 'Docker', 'Machine Learning'],
    location: 'Gurugram, Haryana',
    workMode: 'Hybrid',
    jobType: 'Full Time',
    experienceLevel: 'Entry Level',
    salary: '₹8.0 - 11.0 LPA',
    benefits: ['Hybrid 3-days remote work', 'Annual Tech Conference tickets', 'Health & Wellness allowances', 'Performance bonuses'],
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Junior DevOps Engineer',
    company: 'ScalerOps Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=100&auto=format&fit=crop&q=80',
    description: 'Support cloud infrastructure scaling, continuous integration / continuous delivery (CI/CD) pipelines, and system reliability monitoring across AWS and Docker environments.',
    responsibilities: [
      'Maintain CI/CD pipelines using GitHub Actions and GitLab CI',
      'Containerize applications using Docker and Docker Compose',
      'Assist in provisioning cloud resources on AWS (EC2, S3, RDS)',
      'Monitor server logs, health metrics, and alerting systems',
    ],
    requirements: [
      'Good familiarity with Linux terminal commands and shell scripting (Bash)',
      'Basic understanding of networking concepts (DNS, TCP/IP, HTTP, SSL)',
      'Familiarity with Git and Docker fundamentals',
    ],
    qualifications: [
      'Degree in Computer Science, Information Technology, or self-taught with verified certifications (e.g. AWS Cloud Practitioner)',
    ],
    skills: ['Linux', 'Docker', 'AWS', 'Git', 'CI/CD', 'Bash'],
    location: 'Remote',
    workMode: 'Remote',
    jobType: 'Full Time',
    experienceLevel: 'Entry Level',
    salary: '₹6.0 - 8.0 LPA',
    benefits: ['100% Remote', 'Flexible working hours', 'AWS Certification reimbursement', 'Annual company retreats'],
    postedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'UI/UX & Web Design Intern',
    company: 'CreativePulse Studio',
    companyLogo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=100&auto=format&fit=crop&q=80',
    description: 'Design intuitive interfaces, interactive prototypes, and modern responsive web components. Work directly with our design director to create delightful user journeys.',
    responsibilities: [
      'Design user wireframes, user journeys, and high-fidelity mockups in Figma',
      'Create design system components and maintain consistency across typography and colors',
      'Collaborate with frontend engineers to ensure design fidelity in production',
      'Conduct usability tests and user interviews with student focus groups',
    ],
    requirements: [
      'Proficiency in Figma and modern digital design tools',
      'Solid understanding of typography, spacing, visual hierarchy, and color theory',
      'Basic knowledge of HTML and CSS is a big plus',
    ],
    qualifications: [
      'Design degree, college student, or demonstrable portfolio showing UI/UX case studies',
    ],
    skills: ['Figma', 'UI/UX', 'Wireframing', 'Prototyping', 'HTML5', 'CSS3'],
    location: 'Remote',
    workMode: 'Remote',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹20,000 / month',
    benefits: ['Figma Professional license provided', 'Design mentorship', 'Flexible part-time schedule'],
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Mobile App Developer Intern (Flutter)',
    company: 'AppSphere Mobility',
    companyLogo: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=100&auto=format&fit=crop&q=80',
    description: 'Build fast cross-platform mobile apps for Android and iOS using Flutter and Dart. You will create smooth animations, offline storage, and clean API integrations.',
    responsibilities: [
      'Develop responsive mobile screens and custom widgets using Flutter',
      'Integrate Firebase Authentication, Firestore, and Push Notifications',
      'Connect REST APIs and handle state using Provider or Riverpod',
      'Test app performance on various Android and iOS screen sizes',
    ],
    requirements: [
      'Experience building mobile apps with Flutter & Dart',
      'Basic knowledge of state management concepts',
      'Understanding of mobile design guidelines (Material Design & Cupertino)',
    ],
    qualifications: [
      'Enrolled in B.Tech / BCA / MCA / B.Sc Computer Science',
      'At least one published app on Play Store / GitHub repository demo',
    ],
    skills: ['Flutter', 'Dart', 'Firebase', 'REST API', 'Mobile Development'],
    location: 'Mumbai, Maharashtra',
    workMode: 'Hybrid',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    salary: '₹26,000 / month',
    benefits: ['Travel Allowance', 'Device testing lab provided', 'PPO on successful completion'],
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Backend Developer (Node.js) - Fresher',
    company: 'FinStream Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=80',
    description: 'FinStream is looking for a Junior Backend Developer to design secure banking and payments microservices using Node.js, Express, and MongoDB.',
    responsibilities: [
      'Build secure, scalable RESTful APIs with Node.js and Express',
      'Design efficient MongoDB schemas with proper indexing',
      'Implement authentication, rate limiting, and input sanitization',
      'Write unit tests using Jest and maintain API documentation with Swagger/Postman',
    ],
    requirements: [
      'Proficiency in JavaScript (Node.js) and asynchronous programming',
      'Hands-on experience with MongoDB or relational databases',
      'Understanding of API security, JWT authentication, and HTTPS',
    ],
    qualifications: [
      'B.Tech / B.E. / MCA in CS / IT (2024 / 2025 / 2026 graduates)',
    ],
    skills: ['Node.js', 'Express', 'MongoDB', 'REST API', 'JavaScript', 'Git'],
    location: 'Chennai, Tamil Nadu',
    workMode: 'On-site',
    jobType: 'Full Time',
    experienceLevel: 'Fresher',
    salary: '₹6.0 - 7.5 LPA',
    benefits: ['Health & Life Insurance', 'Annual Bonus', 'Continuous Upskilling & Certifications', 'Relocation Allowance'],
    postedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
];
